### ISSUE TITLE
add support for providing config

### ISSUE THREAD

**Issue by rubiin** [Theodo-UK/nestjs-admin#145]
I don't see an option to specify a config file. It would help people if there was some command to specify the typeorm config file like -c /path-to-config

**Comment by therealedsheenan** [comment]
You can specify the config something like: `typeorm schema:sync --config=<PATH_TO_CONFIG>/config.js`

**Comment by williamdclt** [comment]
I'll close this as https://github.com/Theodo-UK/nestjs-admin/issues/148 is a duplicate with more details.
