### ISSUE TITLE
Example App - Group Name

### ISSUE THREAD

**Issue by julian-iFactory** [Theodo-UK/nestjs-admin#153]
https://github.com/Theodo-UK/nestjs-admin/blob/5b33b27b18e4fd764c11f250764615861482bbbd/exampleApp/src/user/user.module.ts#L21

For creating an admin view for editing the Group Entity shouldn't it be:

`adminSite.register('Group', Group) `

Thank you for creating nestjs-admin its an important feature for a framework. It would be beneficial if the was a demo app in a separate repository - it would make it easier to understand how nestjs-admin is added into a pre-existing site.

**Comment by williamdclt** [comment]
The first argument is the name of the "section" the entity will be displayed in, in the index page of the admin interface (see screenshot). This is just a UI thing.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/15254996/77537979-df604700-6e96-11ea-9389-22d95475a36d.png">

This is here to be consistent with Django Admin where each entity ("model" in Django) is under a section ("app"). But this API probably doesn't make too much sense, this would be a better approach:

```js
adminSite.register(Group, {sectionName: 'User'}) // second argument is some optional options bag 
```
