### ISSUE TITLE
Setup from readme doesn't work on start nestjs app

### ISSUE THREAD

**Issue by mha23** [Theodo-UK/nestjs-admin#166]
[Nest] 63618   - 05/09/2020, 9:44 AM   [ExceptionHandler] Nest cannot export a provider/module that is not a part of the currently processed module (AdminCoreModuleFactory). Please verify whether each exported unit is available in this particular context. +66ms
Error: Nest cannot export a provider/module that is not a part of the currently processed module (AdminCoreModuleFactory). Please verify whether each exported unit is available in this particular context.

**Comment by TheBigBadBunce** [comment]
Fixed in #188. Updating to version 0.4.1 should fix the problem!
