### ISSUE TITLE
Global prefix ignored

### ISSUE THREAD

**Issue by yuriizinets** [Theodo-UK/nestjs-admin#172]
First of all, thank you for such great solution. That's pretty nice project.

After setting global prefix with `app.setGlobalPrefix(...)`, I was able to open initial login page, but all resources and other redirects after that ignores that prefix.

**Comment by yuriizinets** [comment]
Ohh.. I see now. Not noticed that issue for some reason. Thank you for informing me.
I think this issue can be closed now, due to duplicating.

**Comment by potier97** [comment]
hello, has this issue had any updates?
