### ISSUE TITLE
Licensing situation?

### ISSUE THREAD

**Issue by Perni1984** [Theodo-UK/nestjs-admin#187]
Hello @williamdclt,

I was not able to find any info about the current licensing model for nestjs-admin. Is it MIT or some similar license? If yes, could you kindly confirm that or add a proper licensing info to the repository as we might want to use nestjs-admin for one of our products and contribute to it.

Thanks!

**Comment by Perni1984** [comment]
ok, I see that in the package.json file MIT license was mentioned - https://github.com/Theodo-UK/nestjs-admin/blob/09dcaa552a46f93bf260cf786050251c8852d249/package.json#L4

I would suggest just adding a .license file (eventually over githubs add license feature) to make this easily spotable by others that want to use the package.

**Comment by TheBigBadBunce** [comment]
Thanks for the suggestion @Perni1984, we have [added a license file](https://github.com/Theodo-UK/nestjs-admin/commit/3cd1906e25458fd56d0b223030db41afcddc1c8b) 🙂
