### ISSUE TITLE
can login with nestjsadmin

### ISSUE THREAD

**Issue by taosue** [Theodo-UK/nestjs-admin#213]
hey guys , i have install `nestjs-admin` and config it correctly ,

![image](https://user-images.githubusercontent.com/17952537/111023177-80cb0a80-8412-11eb-83ae-ec4a0b9c23ca.png)
![image](https://user-images.githubusercontent.com/17952537/111023194-9f310600-8412-11eb-9f2e-5b97ac4bcf58.png)

and then i try to create an adminuser by `npx nestjs-admin createAdminUser`  and input username and passwd . However , the process havs never ended .

![image](https://user-images.githubusercontent.com/17952537/111023291-1a92b780-8413-11eb-9309-d9d038c59eef.png)

when i check database , i found it insert a record successfully.

![image](https://user-images.githubusercontent.com/17952537/111023332-62b1da00-8413-11eb-892a-76bb6e06c451.png)

when i check the link with `/admin/login` , it show the admin panel . Oh yep , i try to login using the username and passwd which i have entered but fail and print 'Invalid credentials' .

i dont know how to solve it and can u give me some advice.

thx very much , my bro!

**Comment by OoDeLally** [comment]
Same here :/

**Comment by OoDeLally** [comment]
I'm not sure whether the problem comes from `createAdminUser`.
I've manually create a password hash with https://bcrypt-generator.com/, and replaced it in my db's `adminUser.password`.
Now it works, but I don't know why :shrug:

**Comment by alecdewitz** [comment]
Same

**Comment by muhammadsamir11** [comment]
Same here any solution

**Comment by alburkerk** [comment]
Same here

**Comment by OoDeLally** [comment]
Just do what I suggest here https://github.com/Theodo-UK/nestjs-admin/issues/213#issuecomment-798956737

**Comment by redakzter01** [comment]
> I'm not sure whether the problem comes from `createAdminUser`.
> I've manually create a password hash with https://bcrypt-generator.com/, and replaced it in my db's `adminUser.password`.
> Now it works, but I don't know why 🤷

Tried with sqlite as db, the table from the entity has been made and the admin user appear to be correctly insered, however, even changing the user password the login continue to say "Invalid credentials"

**Comment by WintonLi** [comment]
I ran into the same problem. Any progress to fix this issue? There is a PR made a few days ago but it's still under review.

**Comment by yechoi42** [comment]
Same issue here

**Comment by yechoi42** [comment]
https://github.com/Theodo-UK/nestjs-admin/issues/213#issuecomment-798956737 this one also worked for me too

**Comment by gogos-venge** [comment]
Crazy how nobody mentioned that you can simply do a `compare` [here](https://github.com/Theodo-UK/nestjs-admin/blob/32b58eb104883efb98453ff6b56e9ba6c9a5204b/src/adminUser/adminUser.service.ts#L31)
This will fix the issue

**Comment by yylgit** [comment]
m
